Repository liferay/clay, pull requests merged in 2019-03, with the labels that each got.

#1648 Cleaned up commit history for pr#1548
  .babelrc
  .eslintignore
  .eslintrc
  .eslintrc.json
  .prettierignore
  .prettierrc
  .travis.yml
  babel.config.js
  copyright.js
  jest.config.js
  package.json
  packages/browserslist-config-clay/index.js
  packages/clay-badge/README.md
  packages/clay-badge/demo/App.tsx
  packages/clay-badge/demo/index.html
  packages/clay-badge/package.json
  packages/clay-badge/src/ClayBadge.tsx
  packages/clay-badge/src/__tests__/ClayBadge.tsx
  packages/clay-badge/src/__tests__/__snapshots__/ClayBadge.tsx.snap
  packages/clay-badge/tsconfig.declarations.json
  packages/clay-badge/tsconfig.json
  packages/clay-badge/webpack.config.js
  packages/clay-component-boilerplate/.babelrc
  packages/clay-component-boilerplate/README.md
  packages/clay-component-boilerplate/demo/App.js
  packages/clay-component-boilerplate/demo/index.html
  packages/clay-component-boilerplate/package.json
  packages/clay-component-boilerplate/src/__tests__/__snapshots__/index.js.snap
  packages/clay-component-boilerplate/src/__tests__/index.js
  packages/clay-component-boilerplate/src/index.js
  packages/clay-component-boilerplate/webpack.config.js
  packages/generator-clay-component/README.md
  packages/generator-clay-component/__tests__/test-app.js
  packages/generator-clay-component/app/index.js
  packages/generator-clay-component/app/templates/_README.md
  packages/generator-clay-component/app/templates/_package.json
  packages/generator-clay-component/app/templates/_tsconfig.declarations.json
  packages/generator-clay-component/app/templates/_tsconfig.json
  packages/generator-clay-component/app/templates/_webpack.config.js
  packages/generator-clay-component/app/templates/demo/_App.tsx
  packages/generator-clay-component/app/templates/demo/_index.html
  packages/generator-clay-component/app/templates/src/_Boilerplate.tsx
  packages/generator-clay-component/app/templates/src/tests/_Boilerplate.tsx
  packages/generator-clay-component/app/templates/src/tests/__snapshots__/_Boilerplate.tsx.snap
  packages/generator-clay-component/package.json
  scripts/jest-clay-lerna-resolver.js
  scripts/setupTests.js
  tsconfig.declarations.json
  tsconfig.json
  yarn.lock
Labels: 3.x

#1673 Fixes #1571 - Adds a new extension point to only customize the content of the dropdown item
  packages/clay-autocomplete/src/ClayAutocomplete.soy
Labels: type: breaking change

#1688 Revert #1634 - Headers size
  packages/clay-css/src/scss/atlas/variables/_globals.scss
Labels: 2.x, comp: clay-css

#1682 Fixes #1664 Accordion/collapsible sm size
  packages/clay-css/src/content/panels.html
  packages/clay-css/src/content/sidebar.html
  packages/clay-css/src/scss/atlas/variables/_panels.scss
  packages/clay-css/src/scss/components/_panels.scss
  packages/clay-css/src/scss/mixins/_links.scss
  packages/clay-css/src/scss/mixins/_panels.scss
  packages/clay-css/src/scss/variables/_panels.scss
Labels: 3.x

#1700 Fixes #1689 ClayCSS 2.x Toggle Switch add option to use label for="id" markup
  packages/clay-css/src/content/test_toggle_switch_old.html
  packages/clay-css/src/content/toggle_switch.html
  packages/clay-css/src/scss/components/_forms.scss
  packages/clay-css/src/scss/components/_toggle-switch.scss
  packages/clay-css/src/scss/variables/_toggle-switch.scss
Labels: 2.x

#1699 Fixes #1689 ClayCSS Toggle Switch add option to use label for="id" markup
  packages/clay-css/src/content/test_toggle_switch_old.html
  packages/clay-css/src/content/toggle_switch.html
  packages/clay-css/src/scss/components/_forms.scss
  packages/clay-css/src/scss/components/_toggle-switch.scss
  packages/clay-css/src/scss/variables/_toggle-switch.scss
Labels: 3.x

#1440 Fixes #1483, #1484, #1482 - Clay Datepicker and Clay Timepicker
  .eslintrc.json
  .travis.yml
  jest.config.js
  package.json
  packages/clay-charts/package.json
  packages/clay-charts/src/__tests__/__snapshots__/index.js.snap
  packages/clay-charts/src/__tests__/index.js
  packages/clay-css/package.json
  packages/clay-css/src/content/form_elements_date_picker.html
  packages/clay-css/src/images/icons/simple-circle.svg
  packages/clay-css/src/scss/_components.scss
  packages/clay-css/src/scss/_mixins.scss
  packages/clay-css/src/scss/_variables.scss
  packages/clay-css/src/scss/atlas/_variables.scss
  packages/clay-css/src/scss/atlas/variables/_date-picker.scss
  packages/clay-css/src/scss/components/_date-picker.scss
  packages/clay-css/src/scss/components/_input-groups.scss
  packages/clay-css/src/scss/functions/_global-functions.scss
  packages/clay-css/src/scss/mixins/_buttons.scss
  packages/clay-css/src/scss/mixins/_dropdown-menu.scss
  packages/clay-css/src/scss/mixins/_forms.scss
  packages/clay-css/src/scss/mixins/_grid.scss
  packages/clay-css/src/scss/mixins/_input-groups.scss
  packages/clay-css/src/scss/variables/_date-picker.scss
  packages/clay-date-picker/LICENSE.md
  packages/clay-date-picker/README.md
  packages/clay-date-picker/demos/App.tsx
  packages/clay-date-picker/demos/a11y.html
  packages/clay-date-picker/demos/index.html
  packages/clay-date-picker/package.json
  packages/clay-date-picker/src/Button.tsx
  packages/clay-date-picker/src/ClayDatePicker.tsx
  packages/clay-date-picker/src/DateNavigation.tsx
  packages/clay-date-picker/src/DayNumber.tsx
  packages/clay-date-picker/src/DaysTable.tsx
  packages/clay-date-picker/src/Dropdown.tsx
  packages/clay-date-picker/src/Helpers.ts
  packages/clay-date-picker/src/Hooks.ts
  packages/clay-date-picker/src/Icon.tsx
  packages/clay-date-picker/src/InputDate.tsx
  packages/clay-date-picker/src/Select.tsx
  packages/clay-date-picker/src/TimePicker.tsx
  packages/clay-date-picker/src/Weekday.tsx
  packages/clay-date-picker/src/WeekdayHeader.tsx
  packages/clay-date-picker/tsconfig.declarations.json
  packages/clay-date-picker/tsconfig.json
  packages/clay-date-picker/webpack.config.js
  packages/clay-time-picker/LICENSE.md
  packages/clay-time-picker/README.md
  packages/clay-time-picker/demos/App.tsx
  packages/clay-time-picker/demos/a11y.html
  packages/clay-time-picker/demos/index.html
  packages/clay-time-picker/package.json
  packages/clay-time-picker/src/ClayTimePicker.tsx
  packages/clay-time-picker/tsconfig.declarations.json
  packages/clay-time-picker/tsconfig.json
  packages/clay-time-picker/webpack.config.js
  tsconfig.json
  yarn.lock
Labels: 3.x

#1728 Fixes #1579 ClayCSS added a dropdown menu variant `autocomplete-dropdown-menu`
  packages/clay-css/src/content/dropdowns_autocomplete.html
  packages/clay-css/src/content/form_elements.html
  packages/clay-css/src/scss/atlas/variables/_dropdowns.scss
  packages/clay-css/src/scss/components/_dropdowns.scss
  packages/clay-css/src/scss/variables/_dropdowns.scss
Labels: 2.x, comp: clay-css

#1727 Fixes #1579 ClayCSS added a dropdown menu variant `autocomplete-dropdown-menu`
  packages/clay-css/src/content/dropdowns_autocomplete.html
  packages/clay-css/src/content/form_elements.html
  packages/clay-css/src/scss/atlas/variables/_dropdowns.scss
  packages/clay-css/src/scss/components/_dropdowns.scss
  packages/clay-css/src/scss/variables/_dropdowns.scss
Labels: 3.x, comp: clay-css

#1730 Fixes #1721 ClayCSS 2.x Use color variables defined in `_globals.scss`
  packages/clay-css/src/scss/atlas/variables/_date-picker.scss
  packages/clay-css/src/scss/atlas/variables/_modals.scss
  packages/clay-css/src/scss/atlas/variables/_navigation-bar.scss
  packages/clay-css/src/scss/atlas/variables/_popovers.scss
  packages/clay-css/src/scss/variables/_date-picker.scss
Labels: 2.x, comp: clay-css

#1729 Fixes #1721 ClayCSS Use color variables defined in `_globals.scss`
  packages/clay-css/src/scss/atlas/variables/_date-picker.scss
  packages/clay-css/src/scss/atlas/variables/_modals.scss
  packages/clay-css/src/scss/atlas/variables/_navigation-bar.scss
  packages/clay-css/src/scss/atlas/variables/_popovers.scss
  packages/clay-css/src/scss/variables/_date-picker.scss
Labels: 3.x, comp: clay-css

#1717 Fixes #1101 ClayCSS Atlas Popover deprecate variable `$popover-inner-…
  packages/clay-css/src/scss/atlas/variables/_popovers.scss
Labels: 2.x

#1716 Fixes #1101 ClayCSS Atlas remove unused variable `$popover-inner-padd…
  packages/clay-css/src/scss/atlas/variables/_popovers.scss
Labels: 3.x

#1705 Fixes #1669 ClayCSS 2.x added `.form-group-sm` for inputs definition of small size
  packages/clay-css/src/content/form_elements_input_groups.html
  packages/clay-css/src/content/form_group.html
  packages/clay-css/src/content/test_form_group_sm.html
  packages/clay-css/src/scss/atlas/variables/_forms.scss
  packages/clay-css/src/scss/components/_buttons.scss
  packages/clay-css/src/scss/components/_forms.scss
  packages/clay-css/src/scss/components/_input-groups.scss
  packages/clay-css/src/scss/variables/_forms.scss
Labels: 2.x

#1704 Fixes #1669 ClayCSS added `.form-group-sm` for inputs definition of small size
  packages/clay-css/src/content/form_elements_input_groups.html
  packages/clay-css/src/content/form_group.html
  packages/clay-css/src/content/test_form_group_sm.html
  packages/clay-css/src/scss/atlas/variables/_forms.scss
  packages/clay-css/src/scss/components/_buttons.scss
  packages/clay-css/src/scss/components/_forms.scss
  packages/clay-css/src/scss/components/_input-groups.scss
  packages/clay-css/src/scss/variables/_forms.scss
Labels: 3.x
